name: Bug report
description: Create a report to help us improve
title: Please replace with a clear and descriptive title
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting this bug!
  - type: checkboxes
    attributes:
      label: Guidelines
      options:
        - label:
            Please search other issues to make sure this bug has not already
            been reported.
          required: true
        - label:
            If this is related to a typo or the documentation being unclear,
            please click on the relevant page's `Edit` button (pencil icon) and
            suggest a correction instead.
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        Step-by-step instructions on how to reproduce the behavior.
        Example:
        1. Type the following command: [...]
        2. etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Configuration
      placeholder: Command line options and/or configuration file, if any.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Enter the following command in a terminal and copy/paste its output:
        ```bash
        npx envinfo --system --binaries --browsers --npmPackages modern-errors
        ```
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Pull request (optional)
      description:
        Pull requests are welcome! If you would like to help us fix this bug,
        please check our [contributions
        guidelines](../blob/main/CONTRIBUTING.md).
      options:
        - label: I can submit a pull request.
          required: false
